/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int INT_CONST = 6;
  /** RegularExpression Id. */
  int FLOAT_CONST = 7;
  /** RegularExpression Id. */
  int STRING_CONST = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int FLOAT = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int DEF = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int READ = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int NEW = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int OPENP = 26;
  /** RegularExpression Id. */
  int CLOSEP = 27;
  /** RegularExpression Id. */
  int OPENCB = 28;
  /** RegularExpression Id. */
  int CLOSECB = 29;
  /** RegularExpression Id. */
  int OPENB = 30;
  /** RegularExpression Id. */
  int CLOSEB = 31;
  /** RegularExpression Id. */
  int SEMIC = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int EQUALS = 34;
  /** RegularExpression Id. */
  int ASSIGN = 35;
  /** RegularExpression Id. */
  int GREAT = 36;
  /** RegularExpression Id. */
  int LESS = 37;
  /** RegularExpression Id. */
  int GREATEQ = 38;
  /** RegularExpression Id. */
  int LESSEQ = 39;
  /** RegularExpression Id. */
  int DIFF = 40;
  /** RegularExpression Id. */
  int MOD = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"^[A-Za-z]+$\"",
    "\"[0-9]+\"",
    "\"[0-9]*\\\\.[0-9]+\"",
    "\"\\\"[^\\\"]*\\\"\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"def\"",
    "\"break\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"new\"",
    "\"null\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"==\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"%\"",
  };

}
